# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ticnfae
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Problems I couldn't find solutions to, plus my own personal projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.ticnfae.co.uk # the base hostname & protocol for your site
github_username:  pnicholson

# Build settings
markdown: kramdown

google_analytics_tracking_id: UA-26245170-3
